pipeline {
	agent none
	options {
		buildDiscarder(logRotator(numToKeepStr: '10'))
	}
	triggers {
		pollSCM 'H/3 * * * *'
	}
	stages {
		stage('Application Build and Test') {
			options {
		        timeout(time: 1, unit: 'HOURS')
			}
			agent { label 'local' } 
			steps {
				checkout scm
				sh "rm -rf linux-master"
				sh "curl -s https://codeload.github.com/cdaf/linux/zip/refs/heads/master -o linux-master.zip"
				sh "unzip linux-master.zip"
				sh "./linux-master/automation/ci.sh ${env.BUILD_NUMBER} ${env.BRANCH_NAME}"
			}
		}

		stage('DOCKER') {
			agent { label 'local' } 
			steps {
				sh "./release.sh ${env.STAGE_NAME}"
			}
		}

		stage('TEST') {
			when { branch 'master'}
			agent { label 'local' } 
			steps {
				sh "./release.sh ${env.STAGE_NAME}"
			}
		}

		stage ('Product Owner Approval') {
			when { branch 'master'}
			steps {
				emailext (
					subject: "Product Owner Approval pending for ${env.JOB_NAME}",
					body: "${env.BUILD_URL}",
					recipientProviders: [[$class: 'DevelopersRecipientProvider']]
				)
				timeout(time:2, unit:'DAYS') {
					input message:'Deploy to Production?'
				}
			}
		}
		
		stage('PROD') {
			when { branch 'master'}
			agent { label 'local' } 
			steps {
				sh "./release.sh ${env.STAGE_NAME}"
			}
		}
	}
    post {
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
			emailext (
				subject: "Jenkins Job Unstable : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                attachLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)

			
        }
        failure {
            echo 'I failed :('
			emailext (
				subject: "Jenkins Job Failed : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                attachLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)
        }
        changed {
            echo 'Things were different before...'
        }
        always {
            junit '**/target/surefire-reports/*.xml'
        }        
    }	
}
