# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    ./automation/processor/buildPackage.sh $(Build.rev:r) $(Build.SourceBranchName)
    cp TasksLocal $BUILD_ARTIFACTSTAGINGDIRECTORY
    cp *.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
    
- task: PublishBuildArtifacts@1
