jobs:
  - job: 'Build'
    displayName: "dotnet core build and NuGet"
    pool:
      vmImage: ubuntu-20.04
#    pool:
#      name: 'Self-hosted Pool Name'
    steps:

      - task: Bash@3
        displayName: targetlessCD for Feature Branches
        env: 
          GIT_USER: $(GIT_USER)
          GIT_PASS: $(GIT_PASS)
        inputs:
          targetType: inline
          script: |
            curl --silent https://codeload.github.com/cdaf/linux/zip/refs/heads/master -o linux.zip
            unzip linux.zip
            export CDAF_SKIP_CONTAINER_BUILD=yes
            ./linux-master/automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

#          "In-source" Implementation 
#          targetType: filePath
#          filePath: ./automation/entry.sh
#          arguments: $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
