stages:
  - build
  - automated test
  - manual test
  - live

cdaf-ci:
  script: "automation/processor/buildPackage.sh ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}"
  tags:
    - shell
  stage: build
  artifacts:
    paths:
    - TasksLocal/
    - "tram-${CI_BUILD_ID}.tar.gz"

cd:
  stage: automated test
  variables:
    ENV: "CD"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  environment: cd
  dependencies:
  - cdaf-ci

test:
  stage: manual test
  variables:
    ENV: "TEST"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  environment: test
  dependencies:
  - cdaf-ci

production:
  stage: live
  variables:
    ENV: "PROD"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  when: manual
  environment: production
  dependencies:
  - cdaf-ci
