node  {
  properties(
    [
      [
        $class: 'BuildDiscarderProperty',
        strategy: [$class: 'LogRotator', numToKeepStr: '10']
      ],
      pipelineTriggers(
        [
	      [$class: "SCMTrigger", scmpoll_spec: "H/3 * * * *"],
	    ]
	  )
    ]
  )

  stage 'build'
    checkout scm
    sh "cat Jenkinsfile"
    sh "env"
    sh "automation/processor/buildPackage.sh ${BUILD_NUMBER} ${JOB_NAME}"

  stage 'CD'
    sh "TasksLocal/delivery.sh CD ${JOB_NAME}"

  stage 'TEST'
    sh "TasksLocal/delivery.sh TEST ${JOB_NAME}"

  stage 'PROD'
    input 'Ready to go?'
    sh "TasksLocal/delivery.sh PROD"
    archiveArtifacts artifacts: 'TasksLocal/**'
    archiveArtifacts artifacts: '*.gz'
}