name: $(Rev:r)

trigger:
  branches:
    include:
    - '*'

stages:
- stage: DEV
  displayName: CI
#  variables:
#  - group: Git Reader
  jobs:
  - template: templates/azure-pipelines-build-template.yml
    parameters:
      displayName: CDAF build and Package

- stage: TEST
  displayName: User Acceptence Test
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: DEV
#  variables:
#  - group: Web Deploy Test
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: User Acceptence Test
      environment: TEST

- stage: PROD
  displayName: Production Gated Deployment
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: TEST
#  variables:
#  - group: Web Deploy Production
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: Production Gated Deployment
      environment: PROD
