# https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    ./automation/processor/buildPackage.sh $(Build.BuildId) $(Build.SourceBranchName)
    cp -r TasksLocal $BUILD_ARTIFACTSTAGINGDIRECTORY
    cp *.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
    
- task: PublishBuildArtifacts@1
