# https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - '*'

# For a private pool, in this example, named Private requiring the capability of PowerShell
#pool: 
#  name: Azure
#  demands: PowerShell

# or pool with no demands
#pool: Default
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    ./automation/processor/buildPackage.sh $(Build.BuildId) $(Build.SourceBranchName)
    cp -r TasksLocal $BUILD_ARTIFACTSTAGINGDIRECTORY
    cp *.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
    
- task: PublishBuildArtifacts@1
