# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  #virtbox: config.vm.provider 'virtualbox' do |virtualbox, override|
  #virtbox:   virtualbox.linked_clone = true
  #virtbox: end
  #hyper-v: config.vm.provider 'hyperv' do |hyperv, override|
  #hyper-v:   hyperv.auto_start_action = 'Start'
  #hyper-v:   hyperv.linked_clone = true
  #hyper-v:   hyperv.enable_virtualization_extensions = true
  #hyper-v: end
end
