---
project:
  key: TOOL
  plan:
    key: SLAYER
    name: cicd-template
stages:
  - jobs:
      - scripts:
          - '#!/bin/bash'
          - "./automation/processor/buildPackage.sh ${bamboo.buildNumber} ${bamboo.repository.branch.name}"
        interpreter: shell
#        requirements:
#          - system.builder.mvn3.Maven 3
        artifacts:
          - name: Package
            path: '*.gz'
          - name: TasksLocal
            path: 'TasksLocal/**'
