pipeline {
	agent none
	options {
		buildDiscarder(logRotator(numToKeepStr: '10'))
	}
	triggers {
		pollSCM 'H/3 * * * *'
	}
	stages {
		stage('Synchronise with Source Control') {
			options {
		        timeout(time: 1, unit: 'HOURS')
			}
			agent any 
//			agent { label 'osx' } 
			steps {
				checkout scm
			}
		}
    stage('Application Build and Unit Test') {
      options {
            timeout(time: 1, unit: 'HOURS')
      }
      agent any 
      steps {
        sh "chcon -Rt svirt_sandbox_file_t \$(pwd)"
        sh "automation/ci.sh ${BUILD_NUMBER} ${BRANCH_NAME}"
      }
    }
		stage('Packer Image') {
			when { branch 'master'}
			agent any 
			steps {
				sh "TasksLocal/delivery.sh PACKER"
			}
		}
		stage('CD') {
			when { branch 'master'}
			agent any 
			steps {
				sh "TasksLocal/delivery.sh ${env.STAGE_NAME}"
			}
		}

		stage ('Test Manager Approval') {
			when { branch 'master'}
			steps {
				emailext (
					subject: "Test Manager Approval pending for ${env.JOB_NAME}",
					body: "${env.BUILD_URL}",
					recipientProviders: [[$class: 'DevelopersRecipientProvider']]
				)
				timeout(time:1, unit:'DAYS') {
					input message:'Deploy to Acceptence Test?'
				}
			}
		}
		
		stage('TEST') {
			when { branch 'master'}
			agent any 
			steps {
				sh "TasksLocal/delivery.sh ${env.STAGE_NAME}"
			}
		}

		stage ('Product Owner Approval') {
			when { branch 'master'}
			steps {
				emailext (
					subject: "Product Owner Approval pending for ${env.JOB_NAME}",
					body: "${env.BUILD_URL}",
					recipientProviders: [[$class: 'DevelopersRecipientProvider']]
				)
				timeout(time:2, unit:'DAYS') {
					input message:'Deploy to Production?'
				}
			}
		}
		
		stage('PROD') {
			when { branch 'master'}
			agent any 
			steps {
				sh "TasksLocal/delivery.sh ${env.STAGE_NAME}"
			}
		}
	}
    post {
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
			emailext (
				subject: "Jenkins Job Unstable : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                attachLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)
        }
        failure {
            echo 'I failed :('
			emailext (
				subject: "Jenkins Job Failed : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                attachLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)
        }
        changed {
            echo 'Things were different before...'
        }
    }	
}
