node  {
  properties(
    [
      [
        $class: 'BuildDiscarderProperty',
        strategy: [$class: 'LogRotator', numToKeepStr: '10']
      ],
      pipelineTriggers(
        [
	      [$class: "SCMTrigger", scmpoll_spec: "H/3 * * * *"],
	    ]
	  )
    ]
  )
}

if (env.BRANCH_NAME != 'master') {

  node {
    try {

      withEnv(["BRANCH_NAME=${env.BRANCH_NAME}"]) {
        stage ('Application Build and Test') {
          checkout scm
          sh "chcon -Rt svirt_sandbox_file_t \$(pwd)"
          sh "automation/processor/buildPackage.sh ${BUILD_NUMBER} ${BRANCH_NAME}"
        }
      }

    } catch (e) {
    
      currentBuild.result = "FAILED"
      println currentBuild.result
      notifyFailed()
      throw e
    }
  }

} else {

  node {
    try {

      stage ('Application Build and Test') {
        checkout scm
        sh "chcon -Rt svirt_sandbox_file_t \$(pwd)"
        sh "automation/processor/buildPackage.sh ${BUILD_NUMBER} master"
      }

    } catch (e) {
    
      currentBuild.result = "FAILED"
      println currentBuild.result
      notifyFailed()
      throw e
    }
  }

  node {
    try {
      stage ('Packer Image') {
        sh "TasksLocal/delivery.sh PACKER"
      }

      stage ('Tarraform Automated Test') {
        sh "TasksLocal/delivery.sh CD"
      }

    } catch (e) {
    
      currentBuild.result = "FAILED"
      println currentBuild.result
      notifyFailed()
      throw e
    }
  }

  stage ('Test Manager Approval') { input "Deploy to Acceptence Test?" }

  node {
    try {
      stage ('Tarraform Acceptance Test') {
        sh "TasksLocal/delivery.sh TEST"
      }

    } catch (e) {
      currentBuild.result = "FAILED"
      println currentBuild.result
      notifyFailed()
      throw e
    }
  }

  stage ('Product Owner Approval') { input "Deploy to Production?" }

  node {
    try {
      stage ('Tarraform Production') {
        sh "TasksLocal/delivery.sh PROD"
      }

    } catch (e) {
      currentBuild.result = "FAILED"
      println currentBuild.result
      notifyFailed()
      throw e
    }
  }

}

def notifyFailed() {

  emailext (
    recipientProviders: [[$class: 'DevelopersRecipientProvider']],
    subject: "Jenkins Job [${env.JOB_NAME}] Build [${env.BUILD_NUMBER}] failure",
    body: "Check console output at ${env.BUILD_URL}"
  )
}