---
version: 2

plan:
  project-key: CDAF
  key: CDAFL
  name: CDAf Public Contribute

stages:
  - Build Stage:
    - Build Job

Build Job:
  tasks:
    - script:
        - '#!/bin/bash'
        - "./automation/processor/buildPackage.sh ${bamboo.buildNumber} ${bamboo.repository.branch.name}"

  artifacts:
    - name: Package
      pattern: '*.gz'
      shared: true
    - name: TasksLocal
      pattern: 'TasksLocal/**'
      shared: true

---
version: 2

deployment:
  name: CDAFL
  source-plan: CDAF-CDAFL

release-naming:
  next-version-name: ${bamboo.buildNumber}

environments:
  - NO_PROP
  - LINUX

NO_PROP:
  triggers:
    - build-success:
        branch: master
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - '#!/bin/bash'
        - "./TasksLocal/delivery.sh ${bamboo.deploy.environment} ${bamboo.deploy.release}"

LINUX:
  triggers:
    - environment-success: NO_PROP
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - '#!/bin/bash'
        - "./TasksLocal/delivery.sh ${bamboo.deploy.environment} ${bamboo.deploy.release}"
