---
version: 2

plan:
  project-key: CDAF
  key: CDAFL
  name: CDAf Public Contribute

stages:
  - Build Stage:
    - Build Job

Build Job:
  tasks:
    - script:
        - '#!/bin/bash'
        - 'echo "automation" > automation/solution/storeForLocal'
        - 'echo "cat automation/solution/storeForLocal"'
        - 'cat automation/solution/storeForLocal'
        - 'echo "REMOVE ~/.cdaf" > automation/solution/custom/cdaf-deploy.tsk'
        - 'echo "VECOPY automation ~/.cdaf" >> automation/solution/custom/cdaf-deploy.tsk'
        - 'echo "cat automation/solution/custom/cdaf-deploy.tsk"'
        - 'cat automation/solution/custom/cdaf-deploy.tsk'
        - 'echo "context  target     deployTaskOverride" > automation/solution/cdaf.cm'
        - 'echo "local    CDAF       cdaf-deploy.tsk" >>automation/solution/cdaf.cm'
        - 'echo "cat automation/solution/cdaf.cm"'
        - 'cat automation/solution/cdaf.cm'
        - 'ls -al automation/solution'
        - "./automation/processor/buildPackage.sh ${bamboo.buildNumber} ${bamboo.repository.branch.name}"

  artifacts:
    - name: Package
      pattern: '*.gz'
      shared: true
    - name: TasksLocal
      pattern: 'TasksLocal/**'
      shared: true

---
version: 2

deployment:
  name: CDAFL
  source-plan: CDAF-CDAFL

release-naming:
  next-version-name: ${bamboo.buildNumber}

environments:
  - NO_PROP
  - LINUX
  - CDAF

NO_PROP:
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - '#!/bin/bash'
        - "./TasksLocal/delivery.sh ${bamboo.deploy.environment} ${bamboo.deploy.release}"

LINUX:
  triggers:
    - environment-success: NO_PROP
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - '#!/bin/bash'
        - "./TasksLocal/delivery.sh ${bamboo.deploy.environment} ${bamboo.deploy.release}"

CDAF:
  triggers:
    - environment-success: LINUX
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - '#!/bin/bash'
        - "./TasksLocal/delivery.sh ${bamboo.deploy.environment} ${bamboo.deploy.release}"
