version: "3"
services:
    target:
        image: "${TARGET_TAG}"
    test:
        image: "${TEST_TAG}"
        volumes:
          - ${WORK_SPACE}:/solution/workspace
        links:
          - target:target
        depends_on:
          - target
