stages:
  - build
  - targetlessCD
  - staging
  - live

cdaf-ci:
  stage: build
  tags:
    - bash
  script: "automation/entry.sh ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}"
  artifacts:
    paths:
      - release.sh

cd:
  stage: targetlessCD
  tags:
    - bash
  script: "./release.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci

test:
  stage: staging
  tags:
    - bash
  script: "./release.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - bash
  script: "./release.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  when: manual
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master
  