stages:
  - build
  - targetlessCD
  - staging
  - live

cdaf-ci:
  stage: build
  tags:
    - bash
  script: "automation/processor/entry.sh ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}"
  artifacts:
    paths:
    - TasksLocal/
    - "${CI_PROJECT_NAME}-${CI_BUILD_ID}.tar.gz"

cd:
  stage: targetlessCD
  tags:
    - bash
  script: "TasksLocal/delivery.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  environment: "${CI_JOB_STAGE}"
  dependencies:
  - cdaf-ci

test:
  stage: staging
  tags:
    - bash
  script: "TasksLocal/delivery.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  environment: "${CI_JOB_STAGE}"
  dependencies:
  - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - bash
  script: "TasksLocal/delivery.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}"
  when: manual
  environment: "${CI_JOB_STAGE}"
  dependencies:
  - cdaf-ci
  only:
    - master
  