stages:
  - build
  - targetlessCD
  - staging
  - live

cdaf-ci:
  stage: build
  tags:
    - bash
  script: "automation/processor/entry.sh ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}"
  artifacts:
    paths:
    - TasksLocal/
    - "${CI_PROJECT_NAME}-${CI_BUILD_ID}.tar.gz"

cd:
  stage: targetlessCD
  tags:
    - bash
  variables:
    ENV: "CD"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  environment: cd
  dependencies:
  - cdaf-ci

test:
  stage: staging
  tags:
    - bash
  variables:
    ENV: "TEST"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  environment: test
  dependencies:
  - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - bash
  variables:
    ENV: "PROD"
  script: "TasksLocal/delivery.sh ${ENV} ${CI_PIPELINE_ID}"
  when: manual
  environment: production
  dependencies:
  - cdaf-ci
  only:
    - master
  