jobs:
  - job: 'Build'
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ubuntu-20.04
#    pool: # Self-hosted Pool
#      name: Default
#      demands: Agent.OS -equals Linux
    steps:

      - task: Bash@3
        displayName: CDAF Release Build
#        URL and user are not likely to be set as secret, so an explicit mapping is not required, but included for reference
#        env:
#          GIT_URL:  $(GIT_URL)
#          GIT_USER: $(GIT_USER)
#          GIT_PASS: $(GIT_PASS)
        inputs:
          targetType: inline

          # Latest Published Version
          script: |
            curl --silent https://cdaf.io/static/app/downloads/cdaf.sh | bash -
            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # Edge Implementation 
#          script: |
#            curl --silent https://raw.githubusercontent.com/cdaf/linux/master/install.sh | bash -
#            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # In-source Implementation 
#          script: |
#          targetType: filePath
#          filePath: ./automation/entry.sh
#          arguments: $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
