jobs:
  - job: 'Build'
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ubuntu-20.04
#    pool: # Self-hosted Pool
#      name: Default
#      demands: Agent.OS -equals Linux
    steps:

      - task: Bash@3
        displayName: CDAF Release Build
#        URL and user are not likely to be set as secret, so an explicit mapping is not required, but included for reference
#        env:
#          GIT_URL:  $(GIT_URL)
#          GIT_USER: $(GIT_USER)
#          GIT_PASS: $(GIT_PASS)
        inputs:
          targetType: inline

          # Latest Published Version
          script: |
            curl --silent https://cdaf.io/static/app/downloads/cdaf.sh | bash -
            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # Edge Implementation 
#          script: |
#            curl --silent https://raw.githubusercontent.com/cdaf/linux/master/install.sh | bash -
#            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # In-source Implementation 
#          script: |
#          targetType: filePath
#          filePath: ./automation/entry.sh
#          arguments: $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

#      - task: PublishTestResults@2
#        condition: succeededOrFailed()
#        inputs:
#          testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
#          testResultsFiles: '**/test-results/*.xml' 
#          searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
#          mergeTestResults: true # Optional
#          failTaskOnFailedTests: true # Optional
#          testRunTitle: Checkov Results # Optional
#          buildPlatform: # Optional
#          buildConfiguration: # Optional
#          publishRunAttachments: true # Optional
#         condition: always()

#      - task: UseDotNet@2
#        inputs:
#          packageType: sdk
#          version: '10.x'

#      - task: PublishCodeCoverageResults@2
#        displayName: 'Publish code coverage'
#        inputs:
#          codeCoverageTool: 'Cobertura'
#          summaryFileLocation: '**/coverage.cobertura.xml'
#          failIfCoverageEmpty: false

      - task: PublishBuildArtifacts@1
