jobs:
  - job: 'Build'
    displayName: "dotnet core build and NuGet"
    pool:
      vmImage: ubuntu-20.04
#    pool:
#      name: 'Self-hosted Pool Name'
    steps:

      - task: Bash@3
        displayName: targetlessCD for Feature Branches
#        env: 
#          GIT_USER: $(GIT_USER)
#          GIT_PASS: $(GIT_PASS)
        inputs:
          targetType: inline

          # Latest Published Version
          script: |
            curl --silent https://cdaf.io/static/app/downloads/cdaf.sh | bash -
            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # Edge Implementation 
#          script: |
#            curl --silent https://raw.githubusercontent.com/cdaf/linux/master/install.sh | bash -
#            ./automation/entry.sh $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

          # In-source Implementation 
#          script: |
#          targetType: filePath
#          filePath: ./automation/entry.sh
#          arguments: $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
