image: henres/docker-compose-bash

pipelines:
  default:
    - step:
        name: Build and test
        script:
          # Using CDAF Edge
          - curl -s https://codeload.github.com/cdaf/linux/zip/refs/heads/master -o linux-master.zip
          - unzip linux-master.zip
          - ./linux-master/automation/entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH

          # CDAF installed in repo
          # - ./automation/entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH
        services:
          - docker

  branches:
    'master':
      - step:
          name: Build and test
          script:
            - curl -s https://codeload.github.com/cdaf/linux/zip/refs/heads/master -o linux-master.zip
            - unzip linux-master.zip
            - ./linux-master/automation/ci.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH
          artifacts:
            - "release.sh"
          services:
            - docker

      - step:
          name: Deploy to test
          deployment: Test
          script:
            - ./release.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT
          services:
            - docker

      - step:
          name: Deploy to staging
          deployment: Staging
          script:
            - ./release.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT
          services:
            - docker

      - step:
          name: Deploy to production
          deployment: Production
          trigger: manual
          script:
            - ./release.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT
          services:
            - docker