image: cdaf/linux:latest

pipelines:
  default:
    - step:
        name: Build and Test

        services:
          - docker

        # runs-on:
        #   - self.hosted
        #   - linux.shell

        script:
        
          ## CDAF Install is not required because pre-instlled in cdaf/linux:latest, following samples are for use in images without CDAF
          - entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH
          
          # Use Latest Stable
          # - curl -s https://cdaf.io/static/app/downloads/cdaf.sh | bash -
          # - ./automation/entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH

          # Using CDAF Edge
          # - curl -s https://codeload.github.com/cdaf/linux/zip/refs/heads/master -o linux-master.zip
          # - unzip linux-master.zip
          # - ./linux-master/automation/entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH

          # CDAF installed in repo
          # - ./automation/entry.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH

  branches:
    'master':
      - step:
          name: Build Only

          services:
            - docker

          # runs-on:
          #   - self.hosted
          #   - linux.shell

          script:
            - curl -s https://cdaf.io/static/app/downloads/cdaf.sh | bash -
            - ./automation/ci.sh $BITBUCKET_BUILD_NUMBER $BITBUCKET_BRANCH
          artifacts:
            - "release.sh"

      - step:
          name: Docker Test

          services:
            - docker

          # runs-on:
          #   - self.hosted
          #   - linux.shell

          deployment: Test
          script:
            - ./release.sh DOCKER

      - step:
          name: Deploy to staging

          services:
            - docker

          # runs-on:
          #   - self.hosted
          #   - linux.shell

          deployment: Staging
          script:
            - ./release.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT

      - step:
          name: Deploy to production

          services:
            - docker

          # runs-on:
          #   - self.hosted
          #   - linux.shell

          deployment: Production
          trigger: manual
          script:
            - ./release.sh $BITBUCKET_DEPLOYMENT_ENVIRONMENT
