name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Execute all steps on Single Agent
    runs-on: windows-latest
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Execute Compose for all branches
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}

          # Using CDAF Edge
          wget https://codeload.github.com/cdaf/linux/zip/refs/heads/master -O linux-master.zip
          unzip linux-master.zip
          ./linux-master/automation/entry.sh ${GITHUB_RUN_NUMBER} ${GITHUB_REF}

          # CDAF installed in repo
          # ./automation/entry.sh ${GITHUB_RUN_NUMBER} ${GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/master'
        with:
          name: deploy
          path: release.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ env.DOCKERHUB_TOKEN }} && ( github.ref == 'refs/heads/master' )
        with:
          username: cdaf
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: PUSH
        if: ${{ env.DOCKERHUB_TOKEN }} && ( github.ref == 'refs/heads/master' )
        run: |
          cd ${GITHUB_WORKSPACE}/deploy
          chmod +x release.sh
          ./release.sh PUSH
