version: "3"
services:
  target:
    image: "${TARGET_TAG}"

  test:
    image: "${TEST_TAG}"
    volumes:
      - ${WORK_SPACE}:/solution/workspace
    depends_on:
      - target

# For binding to existing networks by name, without this a default NAT will be created
#networks:
#  default:
#    name: nat
#    external: true
