name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: CDAF
        run: |
          cd ${GITHUB_WORKSPACE}
          cp -r samples/crypt/devops solution
          cat solution/CDAF.solution

          ./automation/entry.sh ${GITHUB_RUN_NUMBER} ${GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: release.sh

  NO_PROP:
    if: github.ref == 'refs/heads/master'
    name: Verify nothing attempted when unknown Environment supplied
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: drop
    
      - name: Deploy
        run: |
          cd ${GITHUB_WORKSPACE}/drop
          chmod +x release.sh
          ./release.sh NO_PROP

  LINUX:
    if: github.ref == 'refs/heads/master'
    name: GPG Decryption Test from Sample
    needs: [build, NO_PROP]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: drop
    
      - name: Deploy
        run: |
          cd ${GITHUB_WORKSPACE}/drop
          chmod +x release.sh
          ./release.sh LINUX
