name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Feature Branch Targetless CD
        run: |
          cd ${GITHUB_WORKSPACE}

          # Using CDAF Edge
          wget https://codeload.github.com/cdaf/linux/zip/refs/heads/master -O linux-master.zip
          unzip linux-master.zip
          ./linux-master/automation/entry.sh ${GITHUB_RUN_NUMBER} ${GITHUB_REF}

          # CDAF installed in repo
          # ./automation/entry.sh ${GITHUB_RUN_NUMBER} ${GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v1
        with:
          name: deploy
          path: release.sh

  NO_PROP:
    if: github.ref == 'refs/heads/master'
    name: Verify nothing attempted when unknown Environment supplied
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: deploy
    
      - name: Deploy
        run: |
          cd ${GITHUB_WORKSPACE}/deploy
          chmod +x release.sh
          ./release.sh NO_PROP

  LINUX:
    if: github.ref == 'refs/heads/master'
    name: GPG Decryption Test from Sample
    needs: [build, NO_PROP]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: deploy
    
      - name: Deploy
        run: |
          cd ${GITHUB_WORKSPACE}/deploy
          chmod +x release.sh
          ./release.sh LINUX
